/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package frontend;

import backend.CheckIn;
import backend.Customer;
import backend.Hotel;
import backend.Staff;
import backend.*;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import java.sql.Connection;
import java.sql.Savepoint;
import java.util.ArrayList;
import java.util.Calendar;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author khantil
 */
public class CheckInJFrame extends javax.swing.JFrame {

    /**
     * Creates new form CheckInJFrame
     */
    Hotel selectedHotel;
    int roomNo;
    public CheckInJFrame(Hotel selectedHotel, String hotelName, int roomNo) {
        initComponents();
        this.selectedHotel = selectedHotel;
        this.roomNo = roomNo;
        hotelLabel.setText(""+selectedHotel.getHotelID()+" - "+hotelName);
        roomNoLabel.setText(""+roomNo);
        populateCustomers();
        populateStaffs();
        checkInDateTimeJTextField.setText(Calendar.getInstance().getTime().toString());
    }
    
    private void populateCustomers() {
        customerJComboBox.removeAllItems();
        //statesJComboBox.addItem("");
        //statesJComboBox.addItem("All States");

        try {
            ArrayList<Customer> customersList = Customer.getAllCustomers();
            for (Customer customer : customersList) {
                customerJComboBox.addItem(customer);
            }

        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }
    
    private void populateStaffs() {
        staffJComboBox.removeAllItems();
        //statesJComboBox.addItem("");
        //statesJComboBox.addItem("All States");

        try {
            ArrayList<Staff> staffsList = Staff.getAllStaffsList(selectedHotel.getHotelID());
            for (Staff staff : staffsList) {
                staffJComboBox.addItem(staff);
            }

        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        checkInJButton = new javax.swing.JButton();
        closeButton = new javax.swing.JButton();
        hotelLabel = new javax.swing.JLabel();
        roomNoLabel = new javax.swing.JLabel();
        customerJComboBox = new javax.swing.JComboBox<>();
        staffJComboBox = new javax.swing.JComboBox<>();
        checkInDateTimeJTextField = new javax.swing.JTextField();
        noGuestsJTextField = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Hotel:");

        jLabel2.setText("Room No:");

        jLabel3.setText("Customer:");

        jLabel4.setText("Front Desk Representative:");

        jLabel5.setText("Check-In Date-Time: ");

        jLabel6.setText("Number of Guests:");

        checkInJButton.setText("Check-In");
        checkInJButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                checkInJButtonMouseClicked(evt);
            }
        });

        closeButton.setText("Close");
        closeButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closeButtonMouseClicked(evt);
            }
        });

        hotelLabel.setText("ID _ NAME");

        roomNoLabel.setText("RoomNo");

        checkInDateTimeJTextField.setToolTipText("YYYY-MM-DD HH:MM:SS");

        noGuestsJTextField.setToolTipText("Guests Count");

        jLabel7.setText("Check - In");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(checkInJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(closeButton))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2))
                                .addGap(125, 125, 125)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(roomNoLabel)
                                    .addComponent(hotelLabel)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(staffJComboBox, 0, 252, Short.MAX_VALUE)
                                    .addComponent(customerJComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(checkInDateTimeJTextField)
                                    .addComponent(noGuestsJTextField))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(203, 203, 203)
                .addComponent(jLabel7)
                .addContainerGap(237, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(jLabel1))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(hotelLabel)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(roomNoLabel, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(customerJComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(staffJComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(checkInDateTimeJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(noGuestsJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(checkInJButton)
                    .addComponent(closeButton)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void closeButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeButtonMouseClicked
        WindowEvent winClosingEvent = new WindowEvent(this, WindowEvent.WINDOW_CLOSING);
        Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(winClosingEvent);
        
    }//GEN-LAST:event_closeButtonMouseClicked

//        private boolean statusCode;
//
//    /**
//     * Get the value of statusCode
//     *
//     * @return the value of statusCode
//     */
//    public boolean isStatusCode() {
//        return statusCode;
//    }

    /**
     * Set the value of statusCode
     *
     * @param statusCode new value of statusCode
     */
//    public void setStatusCode(boolean statusCode) {
//        this.statusCode = statusCode;
//    }

    private void checkInJButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_checkInJButtonMouseClicked
        Customer selectedCutomer = (Customer) customerJComboBox.getSelectedItem();
        Staff selectedStaff = (Staff) staffJComboBox.getSelectedItem();
        Savepoint s = null;
        Connection conn = null;
        try{
            conn = Connect.connection;
            conn.setAutoCommit(false);
            s = conn.setSavepoint();
        }catch(Exception e){
            e.printStackTrace();
        }
        int newCheckInCreated;
        if(staffJComboBox.getItemCount()==0){
           newCheckInCreated = CheckIn.createCheckIn(selectedCutomer.getCustomerID(), this.roomNo, this.selectedHotel.getHotelID(), Integer.parseInt(noGuestsJTextField.getText()));
        }else{
            newCheckInCreated = CheckIn.createCheckIn(selectedCutomer.getCustomerID(), this.roomNo, this.selectedHotel.getHotelID(), selectedStaff.getStaffID(), Integer.parseInt(noGuestsJTextField.getText()));
        }
        
         
        String showMessage = "";
        if(newCheckInCreated != -1){
            showMessage = "Customer's ne check-in has been successfully created with Check-In ID = "+newCheckInCreated;
            //this.statusCode = 
            
            
            
            
            
        }else{
            showMessage = "Oops! Some error occured while creating new checkin!";
        }
        
        JOptionPane.showMessageDialog(null,showMessage);
        
        
        
        //Open Bill Window
        CreateBillingInfoJFrame billinInfoJFrame = new CreateBillingInfoJFrame(newCheckInCreated,this.selectedHotel, this.roomNo,this,s);
        billinInfoJFrame.setVisible(true);
        billinInfoJFrame.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        Toolkit tk = Toolkit.getDefaultToolkit();
        Dimension screenSize = tk.getScreenSize();
        int screenHeight = screenSize.height;
        int screenWidth = screenSize.width;
        billinInfoJFrame.setLocation(screenWidth/4,screenHeight/4);
//        if(newCheckInCreated != -1 && this.statusCode == true){
//            try{
//                conn.commit();
//                JOptionPane.showMessageDialog(null, "Both transactions executed correctly");
//            }catch(Exception e){
//                e.printStackTrace();
//            }
//        }else{
//            try{
//                conn.rollback(s);
//                JOptionPane.showMessageDialog(null, "One of the transactions did not execute");
//            }catch(Exception e){
//                e.printStackTrace();
//            }
//        }
//        try{
//            conn.setAutoCommit(true);
//        }catch(Exception e){
//            e.printStackTrace();
//        }

        WindowEvent winClosingEvent = new WindowEvent(this, WindowEvent.WINDOW_CLOSING);
        Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(winClosingEvent);
    }//GEN-LAST:event_checkInJButtonMouseClicked

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(CheckInJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(CheckInJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(CheckInJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(CheckInJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new CheckInJFrame().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField checkInDateTimeJTextField;
    private javax.swing.JButton checkInJButton;
    private javax.swing.JButton closeButton;
    private javax.swing.JComboBox<Customer> customerJComboBox;
    private javax.swing.JLabel hotelLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField noGuestsJTextField;
    private javax.swing.JLabel roomNoLabel;
    private javax.swing.JComboBox<Staff> staffJComboBox;
    // End of variables declaration//GEN-END:variables
}
