/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package frontend;

import java.awt.Dimension;
import java.awt.Toolkit;
import javax.swing.JFrame;

/**
 *
 * @author Dax Amin
 */
public class ReportsJFrame extends javax.swing.JFrame {

    /**
     * Creates new form ReportsJFrame
     */
    public ReportsJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        occupancyHotelButton = new javax.swing.JButton();
        occupancyCityButton = new javax.swing.JButton();
        OccupancyRoomTypeButton = new javax.swing.JButton();
        checkInsDateButton = new javax.swing.JButton();
        staffGroupedButton = new javax.swing.JButton();
        revenueButton = new javax.swing.JButton();
        staffByRoleHotel = new javax.swing.JButton();
        percentOccupancyButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Reports");

        occupancyHotelButton.setText("Occupancy by Hotel");
        occupancyHotelButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                occupancyHotelButtonMouseClicked(evt);
            }
        });

        occupancyCityButton.setText("Occupancy by City");
        occupancyCityButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                occupancyCityButtonMouseClicked(evt);
            }
        });

        OccupancyRoomTypeButton.setText("Occupancy By Room Type");
        OccupancyRoomTypeButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                OccupancyRoomTypeButtonMouseClicked(evt);
            }
        });

        checkInsDateButton.setText("CheckIns between Date Range");
        checkInsDateButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                checkInsDateButtonMouseClicked(evt);
            }
        });

        staffGroupedButton.setText("Staff Grouped By Thier Role");
        staffGroupedButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                staffGroupedButtonMouseClicked(evt);
            }
        });

        revenueButton.setText("Revenue");
        revenueButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                revenueButtonMouseClicked(evt);
            }
        });

        staffByRoleHotel.setText("Staff Groped By Hotel & Role");
        staffByRoleHotel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                staffByRoleHotelActionPerformed(evt);
            }
        });

        percentOccupancyButton.setText("Percentage Occupancy");
        percentOccupancyButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                percentOccupancyButtonMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(263, 263, 263)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(staffGroupedButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(occupancyCityButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(occupancyHotelButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(checkInsDateButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(OccupancyRoomTypeButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(revenueButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(66, 66, 66)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(staffByRoleHotel, javax.swing.GroupLayout.DEFAULT_SIZE, 192, Short.MAX_VALUE)
                            .addComponent(percentOccupancyButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(105, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(occupancyHotelButton))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(staffByRoleHotel)))
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(occupancyCityButton)
                    .addComponent(percentOccupancyButton))
                .addGap(31, 31, 31)
                .addComponent(OccupancyRoomTypeButton)
                .addGap(33, 33, 33)
                .addComponent(checkInsDateButton)
                .addGap(34, 34, 34)
                .addComponent(staffGroupedButton)
                .addGap(36, 36, 36)
                .addComponent(revenueButton)
                .addContainerGap(71, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void occupancyHotelButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_occupancyHotelButtonMouseClicked
        // TODO add your handling code here:
        OccupancyHotelJFrame occupancyHotelJFrame = new OccupancyHotelJFrame();
        occupancyHotelJFrame.setVisible(true);
        occupancyHotelJFrame.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        Toolkit tk = Toolkit.getDefaultToolkit();
        Dimension screenSize = tk.getScreenSize();
        int screenHeight = screenSize.height;
        int screenWidth = screenSize.width;
        occupancyHotelJFrame.setLocation(screenWidth/4,screenHeight/4);
    }//GEN-LAST:event_occupancyHotelButtonMouseClicked

    private void OccupancyRoomTypeButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_OccupancyRoomTypeButtonMouseClicked
        // TODO add your handling code here:
        OccupancyRoomTypeJFrame occupancyRoomTypeJFrame = new OccupancyRoomTypeJFrame();
        occupancyRoomTypeJFrame.setVisible(true);
        occupancyRoomTypeJFrame.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        Toolkit tk = Toolkit.getDefaultToolkit();
        Dimension screenSize = tk.getScreenSize();
        int screenHeight = screenSize.height;
        int screenWidth = screenSize.width;
        occupancyRoomTypeJFrame.setLocation(screenWidth/4,screenHeight/4);
    }//GEN-LAST:event_OccupancyRoomTypeButtonMouseClicked

    private void occupancyCityButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_occupancyCityButtonMouseClicked
        // TODO add your handling code here:
        OccupancyCityJFrame occupancyCityJFrame = new OccupancyCityJFrame();
        occupancyCityJFrame.setVisible(true);
        occupancyCityJFrame.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        Toolkit tk = Toolkit.getDefaultToolkit();
        Dimension screenSize = tk.getScreenSize();
        int screenHeight = screenSize.height;
        int screenWidth = screenSize.width;
        occupancyCityJFrame.setLocation(screenWidth/4,screenHeight/4);
    }//GEN-LAST:event_occupancyCityButtonMouseClicked

    private void checkInsDateButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_checkInsDateButtonMouseClicked
        // TODO add your handling code here:
        DateSelectReportJFrame dateSelectReportJFrame = new DateSelectReportJFrame();
        dateSelectReportJFrame.setVisible(true);
        dateSelectReportJFrame.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        Toolkit tk = Toolkit.getDefaultToolkit();
        Dimension screenSize = tk.getScreenSize();
        int screenHeight = screenSize.height;
        int screenWidth = screenSize.width;
        dateSelectReportJFrame.setLocation(screenWidth/4,screenHeight/4);
    }//GEN-LAST:event_checkInsDateButtonMouseClicked

    private void staffGroupedButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_staffGroupedButtonMouseClicked
        // TODO add your handling code here:
        StaffGroupedJFrame staffGroupedJFrame = new StaffGroupedJFrame();
        staffGroupedJFrame.setVisible(true);
        staffGroupedJFrame.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        Toolkit tk = Toolkit.getDefaultToolkit();
        Dimension screenSize = tk.getScreenSize();
        int screenHeight = screenSize.height;
        int screenWidth = screenSize.width;
        staffGroupedJFrame.setLocation(screenWidth/4,screenHeight/4);
    }//GEN-LAST:event_staffGroupedButtonMouseClicked

    private void revenueButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_revenueButtonMouseClicked
        // TODO add your handling code here:
        dateForRevenueJFrame dateForRevenueJFrame  = new dateForRevenueJFrame();
        dateForRevenueJFrame.setVisible(true);
        dateForRevenueJFrame.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        Toolkit tk = Toolkit.getDefaultToolkit();
        Dimension screenSize = tk.getScreenSize();
        int screenHeight = screenSize.height;
        int screenWidth = screenSize.width;
        dateForRevenueJFrame.setLocation(screenWidth/4,screenHeight/4);
    }//GEN-LAST:event_revenueButtonMouseClicked

    private void staffByRoleHotelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_staffByRoleHotelActionPerformed
        // TODO add your handling code here:
        StaffRoleHotelJFrame staffRoleHotelJFrame = new StaffRoleHotelJFrame();
        staffRoleHotelJFrame.setVisible(true);
        staffRoleHotelJFrame.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        Toolkit tk = Toolkit.getDefaultToolkit();
        Dimension screenSize = tk.getScreenSize();
        int screenHeight = screenSize.height;
        int screenWidth = screenSize.width;
        staffRoleHotelJFrame.setLocation(screenWidth/4,screenHeight/4);
    }//GEN-LAST:event_staffByRoleHotelActionPerformed

    private void percentOccupancyButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_percentOccupancyButtonMouseClicked
        // TODO add your handling code here:
        PercentOccupancyJFrame percentOccupancyJFrame = new PercentOccupancyJFrame();
        percentOccupancyJFrame.setVisible(true);
        percentOccupancyJFrame.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        Toolkit tk = Toolkit.getDefaultToolkit();
        Dimension screenSize = tk.getScreenSize();
        int screenHeight = screenSize.height;
        int screenWidth = screenSize.width;
        percentOccupancyJFrame.setLocation(screenWidth/4,screenHeight/4);
    }//GEN-LAST:event_percentOccupancyButtonMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ReportsJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ReportsJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ReportsJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ReportsJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ReportsJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton OccupancyRoomTypeButton;
    private javax.swing.JButton checkInsDateButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton occupancyCityButton;
    private javax.swing.JButton occupancyHotelButton;
    private javax.swing.JButton percentOccupancyButton;
    private javax.swing.JButton revenueButton;
    private javax.swing.JButton staffByRoleHotel;
    private javax.swing.JButton staffGroupedButton;
    // End of variables declaration//GEN-END:variables
}
