/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package frontend;

import backend.Hotel;
import backend.Room;
import static frontend.EditRoomJFrame.hotel;
import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author khantil
 */
public class RoomAvailabilityJFrame extends javax.swing.JFrame {

    /**
     * Creates new form RoomAvailabilityJFrame
     */
    Hotel selectedHotel;
    public RoomAvailabilityJFrame(Hotel selectedHotel) {
        initComponents();
        this.selectedHotel = selectedHotel;
        populateRooms();
    }
    
    private void populateRooms() {
        roomJComboBox.removeAllItems();
        //statesJComboBox.addItem("");
        //statesJComboBox.addItem("All States");

        try {
            ArrayList<Room> roomsList = Room.getAllRoomsList(selectedHotel.getHotelID());
            for (Room room : roomsList) {
                System.out.println(room.getRoomNo());
                roomJComboBox.addItem(room);
            }

        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        availabilityButtonGroup = new javax.swing.ButtonGroup();
        roomJComboBox = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        hotelJLabel = new javax.swing.JLabel();
        availableJRadioButton = new javax.swing.JRadioButton();
        notAvailableJRadioButton = new javax.swing.JRadioButton();
        updateJButton = new javax.swing.JButton();
        closeJButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        roomJComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                roomJComboBoxActionPerformed(evt);
            }
        });

        jLabel1.setText("Select Room:");

        jLabel2.setText("Hotel:");

        hotelJLabel.setText("jLabel3");

        availabilityButtonGroup.add(availableJRadioButton);
        availableJRadioButton.setText("Available");

        availabilityButtonGroup.add(notAvailableJRadioButton);
        notAvailableJRadioButton.setText("Not Available");

        updateJButton.setText("Update");
        updateJButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                updateJButtonMouseClicked(evt);
            }
        });

        closeJButton.setText("Close");
        closeJButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closeJButtonMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(availableJRadioButton)
                            .addComponent(hotelJLabel)
                            .addComponent(roomJComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(notAvailableJRadioButton)
                                .addGap(0, 63, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(updateJButton)))
                        .addGap(18, 18, 18)
                        .addComponent(closeJButton)
                        .addGap(16, 16, 16))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(hotelJLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(roomJComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addComponent(availableJRadioButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(notAvailableJRadioButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(updateJButton)
                    .addComponent(closeJButton))
                .addGap(21, 21, 21))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void updateJButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_updateJButtonMouseClicked
        // TODO add your handling code here:
        Room selectedRoom = (Room) roomJComboBox.getSelectedItem();
        boolean availability = true;
        if(availableJRadioButton.isSelected()){
            availability = true;
        }else{
            availability = false;
        }
        
        Room.updateRoomAvailability(selectedRoom.getRoomNo(), selectedRoom.getHotelID(), availability);
        JOptionPane.showMessageDialog(null,"Selected Room has been successfully updated for availability!");
        WindowEvent winClosingEvent = new WindowEvent(this, WindowEvent.WINDOW_CLOSING);
        Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(winClosingEvent);
    }//GEN-LAST:event_updateJButtonMouseClicked

    private void closeJButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeJButtonMouseClicked
        // TODO add your handling code here:
        WindowEvent winClosingEvent = new WindowEvent(this, WindowEvent.WINDOW_CLOSING);
        Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(winClosingEvent);
    }//GEN-LAST:event_closeJButtonMouseClicked

    private void roomJComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_roomJComboBoxActionPerformed
        // TODO add your handling code here:
        Room selectedRoom = (Room) roomJComboBox.getSelectedItem();
        if(selectedRoom.isAvailability()){
             System.out.println("\n Room is available");
            availableJRadioButton.setSelected(true);
            //notAvailableJRadioButton.setSelected(false);
        }else{
            System.out.println("\n Room is not available");
            //availableJRadioButton.setSelected(false);
            notAvailableJRadioButton.setSelected(true);
        }
    }//GEN-LAST:event_roomJComboBoxActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(RoomAvailabilityJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(RoomAvailabilityJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(RoomAvailabilityJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(RoomAvailabilityJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new RoomAvailabilityJFrame().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup availabilityButtonGroup;
    private javax.swing.JRadioButton availableJRadioButton;
    private javax.swing.JButton closeJButton;
    private javax.swing.JLabel hotelJLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JRadioButton notAvailableJRadioButton;
    private javax.swing.JComboBox<Room> roomJComboBox;
    private javax.swing.JButton updateJButton;
    // End of variables declaration//GEN-END:variables
}
